// <copyright file="PreValidationcontactCreate.cs" company="">
// Copyright (c) 2023 All Rights Reserved
// </copyright>
// <author></author>
// <date>3/30/2023 2:35:37 PM</date>
// <summary>Implements the PreValidationcontactCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.IO;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using System.Text.Json.Serialization;
using System.Xml;
using Microsoft.Xrm.Sdk;

namespace PowerPlatform.Demo.Plugins
{

    /// <summary>
    /// PreValidationcontactCreate Plugin.
    /// </summary>    
    public class GenericPlugin : PluginBase
    {
        public GenericPlugin(string unsecure, string secure)
            : base(typeof(GenericPlugin))
        {

            // TODO: Implement your custom configuration handling.
        }


        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
           

            // Obtain the tracing service
            ITracingService tracingService = localContext.TracingService;
            //var dump = ObjectDumper.Dump(localContext.PluginExecutionContext);
            //tracingService.Trace(dump);


            var target = localContext.PluginExecutionContext.InputParameters["Target"];
            var dump = ObjectDumper.Dump(target);
            tracingService.Trace(dump);
        }


    }
}
